
alexApp.controller('popupCtrl',['$scope', function($scope){

            function init(){
                $scope.initialPopupMessage = 'this is generated by popup controller'; 
            }    
            
            init();
        }]);